query InvitationCommissionConnection($after: String) {
  invitationCommissionConnection(after: $after) {
    nodes {
      id
      amount
      transferType
      traceId
      snapshotId
      asset {
        name
        symbol
        iconUrl
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
