query Market($id: ID) {
  market(id: $id) {
    id
    favorited
    baseAsset {
      assetId
      symbol
      iconUrl
      priceUsd
      changeUsd
    }
    quoteAsset {
      assetId
      symbol
      iconUrl
      priceUsd
    }
    oceanMarketId
  }
}
