query Market($id: ID, $quoteAssetId: String, $baseAssetId: String) {
  market(id: $id, quoteAssetId: $quoteAssetId, baseAssetId: $baseAssetId) {
    id
    favorited
    baseAsset {
      assetId
      symbol
      iconUrl
      priceUsd
      changeUsd
      chainAsset {
        iconUrl
      }
    }
    quoteAsset {
      assetId
      symbol
      iconUrl
      priceUsd
      chainAsset {
        iconUrl
      }
    }
    oceanMarketId
  }
}
