query MarketConnection($type: String!, $after: String, $query: String) {
  marketConnection(type: $type, after: $after, query: $query) {
    nodes {
      id
      baseAsset {
        assetId
        symbol
        iconUrl
        changeUsd
        priceUsd
      }
      quoteAsset {
        assetId
        symbol
        iconUrl
      }
      oceanMarketId
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
