query OceanOrderConnection($marketId: ID, $after: String, $filter: String) {
  oceanOrderConnection(marketId: $marketId, after: $after, filter: $filter) {
    nodes {
      id
      traceId
      orderType
      side
      amount
      funds
      filledAmount
      filledFunds
      remainingAmount
      remainingFunds
      price
      state
      marketId
      baseAsset {
        assetId
        symbol
        iconUrl
        chainAsset {
          iconUrl
        }
      }
      quoteAsset {
        assetId
        symbol
        iconUrl
        chainAsset {
          iconUrl
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
