query UserAssets {
  userAssets {
    assetId
    name
    symbol
    iconUrl
    chainId
    balance
    balanceUsd
    priceUsd
    changeUsd
    changeBtc
    chainAsset {
      iconUrl
    }
  }
}
