development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: mixcoin_plus_development
  pool:     10
  username: postgres
  password: postgres
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: mixcoin_plus_test
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 32 } %>
  url: <%= ENV['DATABASE_URL'] %>
