sync_mixin_asset_price_worker:
  cron: '*/10 * * * *'
  class: 'MixinAssetSyncPriceWorker'
recommended_markets_sync_trades_from_engine_worker:
  cron: '* * * * *'
  class: 'RecommendedMarketsSyncTradesFromEngineWorker'
