sync_mixin_asset_price_worker:
  cron: '*/15 * * * *'
  class: 'MixinAssetSyncPriceWorker'
batch_mixin_transfer_process_worker:
  cron: '*/2 * * * *'
  class: 'BatchMixinTransferProcessWorker'
recommended_markets_sync_trades_from_engine_worker:
  cron: '* * * * *'
  class: 'RecommendedMarketsSyncTradesFromEngineWorker'
arbitrage_orders_timeout_worker:
  cron: '* * * * *'
  class: 'ArbitrageOrdersTimeoutWorker'
booking_order_snapshot_generate_worker:
  cron: '* * * * *'
  class: 'BookingOrderSnapshotGenerateWorker'
booking_order_activity_generate_worker:
  cron: '5 0 * * *'
  class: 'BookingOrderActivityGenerateWorker'
batch_market_generate_price_records_worker:
  cron: '0 * * * *'
  class: 'BatchMarketGeneratePriceRecordsWorker'
