query AppletConnection($after: String) {
  appletConnection(after: $after) {
    nodes {
      id
      number
      title
      connected
      lastActiveAt
      appletTriggers {
        ... on AppletDatetimeTrigger {
          type
          description
          minute
          hour
          day
          month
          wday
        }
      }
      appletActions {
        ... on Applet4swapAction {
          type
          description
          payAssetId
          fillAssetId
          payAmount
          slippage
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
  currentUser {
    ifttbBrokerId
    ifttbRole
    mayCreateApplet
  }
}
