query Applet($id: ID!) {
  applet(id: $id) {
    id
    number
    title
    connected
    lastActiveAt
    profit
    payTotal
    fillTotal
    payAsset {
      assetId
      symbol
      iconUrl
      priceUsd
    }
    fillAsset {
      assetId
      symbol
      iconUrl
      priceUsd
    }
    appletTriggers {
      ... on AppletDatetimeTrigger {
        id
        type
        description
        params
        minute
        hour
        day
        month
        wday
      }
      ... on Applet4swapTrigger {
        id
        type
        description
        params
        baseAssetId
        quoteAssetId
        targetValue
        targetIndex
        compareAction
      }
    }
    appletActions {
      ... on Applet4swapAction {
        id
        type
        description
        params
        payAssetId
        fillAssetId
        payAmount
        slippage
      }
      ... on AppletMixSwapAction {
        id
        type
        description
        params
        payAssetId
        fillAssetId
        payAmount
        slippage
      }
    }
  }
}
