query Applet($id: ID!) {
  applet(id: $id) {
    id
    number
    title
    connected
    lastActiveAt
    profit
    payTotal
    payTotalUsd
    fillTotal
    fillTotalUsd
    appletActivitiesCompletedCount
    archivedAt
    payAsset {
      assetId
      symbol
      iconUrl
      priceUsd
    }
    fillAsset {
      assetId
      symbol
      iconUrl
      priceUsd
    }
    appletTriggers {
      ... on AppletDatetimeTrigger {
        id
        type
        params {
          description
          minute
          hour
          day
          month
          wday
        }
      }
      ... on Applet4swapTrigger {
        id
        type
        params {
          description
          baseAssetId
          quoteAssetId
          targetValue
          targetIndex
          compareAction
        }
        quoteAsset {
          assetId
          iconUrl
          symbol
          priceUsd
          chainAsset {
            assetId
            iconUrl
            symbol
          }
        }
        baseAsset {
          assetId
          iconUrl
          symbol
          priceUsd
          chainAsset {
            assetId
            iconUrl
            symbol
          }
        }
      }
    }
    appletActions {
      ... on Applet4swapAction {
        id
        type
        params {
          description
          payAssetId
          fillAssetId
          payAmount
          slippage
        }
        payAsset {
          assetId
          iconUrl
          symbol
          priceUsd
          chainAsset {
            assetId
            iconUrl
            symbol
          }
        }
        fillAsset {
          assetId
          iconUrl
          symbol
          priceUsd
          chainAsset {
            assetId
            iconUrl
            symbol
          }
        }
      }
      ... on AppletMixSwapAction {
        id
        type
        params {
          description
          payAssetId
          fillAssetId
          payAmount
          slippage
        }
        payAsset {
          assetId
          iconUrl
          symbol
          priceUsd
          chainAsset {
            assetId
            iconUrl
            symbol
          }
        }
        fillAsset {
          assetId
          iconUrl
          symbol
          priceUsd
          chainAsset {
            assetId
            iconUrl
            symbol
          }
        }
      }
      ... on AppletAlertAction {
        id
        type
        params {
          description
          via
          data
        }
      }
    }
  }
}
