query Applet($id: ID!) {
  applet(id: $id) {
    id
    number
    title
    connected
    lastActiveAt
    profit
    payTotal
    fillTotal
    payAsset {
      assetId
      symbol
      iconUrl
      priceUsd
    }
    fillAsset {
      assetId
      symbol
      iconUrl
      priceUsd
    }
    appletTriggers {
      ... on AppletDatetimeTrigger {
        id
        type
        params
      }
      ... on Applet4swapTrigger {
        id
        type
        params
      }
    }
    appletActions {
      ... on Applet4swapAction {
        id
        type
        params
      }
      ... on AppletMixSwapAction {
        id
        type
        params
      }
    }
  }
}
