query AppletConnection($after: String) {
  appletConnection(after: $after) {
    nodes {
      id
      number
      title
      connected
      appletActivitiesCount
      lastActiveAt
      appletTriggers {
        ... on AppletDatetimeTrigger {
          type
          params {
            description
            minute
            hour
            day
            month
            wday
          }
        }
        ... on Applet4swapTrigger {
          type
          params {
            description
            baseAssetId
            quoteAssetId
            targetValue
            targetIndex
            compareAction
          }
        }
      }
      appletActions {
        ... on Applet4swapAction {
          type
          params {
            description
            payAssetId
            fillAssetId
            payAmount
            slippage
          }
        }
        ... on AppletMixSwapAction {
          type
          params {
            description
            payAssetId
            fillAssetId
            payAmount
            slippage
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
  currentUser {
    ifttbBrokerId
    ifttbRole
    mayCreateApplet
  }
}
