query AdminAppletConnection($filter: String, $userId: ID, $after: String) {
  adminAppletConnection(filter: $filter, userId: $userId, after: $after) {
    nodes {
      id
      number
      title
      connected
      appletActivitiesCount
      lastActiveAt
      cron
      frequency
      user {
        id
        mixinUuid
        mixinId
        name
        avatar
      }
      archivedAt
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
