query AdminMixinNetworkSnapshotConnection(
  $after: String
  $oceanOrderId: ID
  $swapOrderId: ID
  $snapshotType: String
) {
  adminMixinNetworkSnapshotConnection(
    after: $after
    oceanOrderId: $oceanOrderId
    swapOrderId: $swapOrderId
    snapshotType: $snapshotType
  ) {
    nodes {
      id
      type
      snapshotType
      traceId
      snapshotId
      amount
      data
      opponentId
      opponent {
        avatar
        name
        mixinId
      }
      asset {
        assetId
        symbol
        name
        iconUrl
      }
      processedAt
      transferredAt
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
