query AdminUserConnection($after: String, $query: String, $order: String) {
  adminUserConnection(after: $after, query: $query, order: $order) {
    nodes {
      id
      name
      avatar
      mixinId
      mixinUuid
      invitationsCount
      oceanOrdersCount
      lastActiveAt
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
