query AdminUserConnection($after: String) {
  adminUserConnection(after: $after) {
    nodes {
      id
      name
      avatar
      mixinId
      mixinUuid
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
