query AdminMarketConnection(
  $after: String
  $query: String
  $quoteAssetId: String
) {
  adminMarketConnection(
    after: $after
    query: $query
    quoteAssetId: $quoteAssetId
  ) {
    nodes {
      id
      oceanMarketId
      oceanOrdersCount
      tradesCount
      recommended
      baseAsset {
        assetId
        symbol
        iconUrl
      }
      quoteAsset {
        assetId
        symbol
        iconUrl
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
