query AdminOceanOrder($id: ID!) {
  adminOceanOrder(id: $id) {
    id
    traceId
    state
    conversationId
    side
    orderType
    price
    amount
    funds
    remainingAmount
    remainingFunds
    filledAmount
    filledFunds
    user {
      avatar
      name
      mixinId
    }
    broker {
      mixinUuid
    }
    baseAsset {
      assetId
      symbol
      iconUrl
    }
    quoteAsset {
      assetId
      symbol
      iconUrl
    }
    createdAt
  }
}
