query AdminBookingOrderActivityParticipantConnection(
  $after: String
  $userId: ID
  $bookingOrderActivityId: ID
  $state: String
) {
  adminBookingOrderActivityParticipantConnection(
    after: $after
    userId: $userId
    bookingOrderActivityId: $bookingOrderActivityId
    state: $state
  ) {
    nodes {
      id
      state
      bonus
      scores
      scoresRatio
      scoresTotal
      bookingOrderActivity {
        bonusTotal
        scoresTotal
        startedAt
        endedAt
        market {
          baseAsset {
            assetId
            symbol
          }
          quoteAsset {
            assetId
            symbol
          }
        }
      }
      bonusAsset {
        assetId
        symbol
      }
      user {
        name
        avatar
        mixinId
        mixinUuid
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
