query AdminMarket($id: ID!) {
  adminMarket(id: $id) {
    id
    oceanMarketId
    oceanOrdersCount
    tradesCount
    hiddenAt
    bookingOrderActivityEnable
    baseAsset {
      assetId
      symbol
      iconUrl
    }
    quoteAsset {
      assetId
      symbol
      iconUrl
    }
    createdAt
  }
}
