query AdminUser($id: ID!) {
  adminUser(id: $id) {
    id
    name
    avatar
    mixinId
    mixinUuid
    oceanBroker {
      mixinUuid
    }
    invitor {
      name
      avatar
      mixinId
    }
    createdAt
  }
}
