query AdminArbitrageOrderConnection(
  $after: String
  $state: String
  $marketId: ID
  $arbitragerId: ID
) {
  adminArbitrageOrderConnection(
    after: $after
    state: $state
    marketId: $marketId
    arbitragerId: $arbitragerId
  ) {
    nodes {
      id
      state
      expectedProfit
      netProfit
      raw
      arbitrager {
        name
        mixinUuid
      }
      market {
        baseAsset {
          assetId
          symbol
        }
        quoteAsset {
          assetId
          symbol
        }
      }
      profitAsset {
        assetId
        symbol
        iconUrl
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
