query AdminApplet($id: ID!) {
  adminApplet(id: $id) {
    id
    number
    title
    connected
    lastActiveAt
    cron
    frequency
    profit
    payTotal
    fillTotal
    payAsset {
      assetId
      symbol
      iconUrl
      priceUsd
    }
    fillAsset {
      assetId
      symbol
      iconUrl
      priceUsd
    }
    user {
      id
      mixinUuid
      mixinId
      name
      avatar
    }
    archivedAt
    createdAt
  }
}
