query AdminAppStatistic($scope: String) {
  adminAppStatistic(scope: $scope) {
    usersCount
    validOrdersCount
    marketsCount
    matchTotalUsd
    feeTotalUsd
    invitationCommissionTotalUsd
    groupOwnerCommissionTotalUsd
    unprocessedSnapshotsCount
    unprocessedTransfersCount
  }
}
