query AdminMixinTransferConnection(
  $after: String
  $oceanOrderId: ID
  $swapOrderId: ID
  $userId: ID
  $opponentId: ID
  $transferType: String
) {
  adminMixinTransferConnection(
    after: $after
    oceanOrderId: $oceanOrderId
    swapOrderId: $swapOrderId
    userId: $userId
    opponentId: $opponentId
    transferType: $transferType
  ) {
    nodes {
      id
      transferType
      traceId
      snapshotId
      amount
      memo
      opponentId
      userId
      recipient {
        avatar
        name
        mixinId
      }
      asset {
        assetId
        symbol
        name
        iconUrl
      }
      processedAt
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
