query AdminMarketConnection($after: String) {
  adminMarketConnection(after: $after) {
    nodes {
      id
      oceanMarketId
      oceanOrdersCount
      tradesCount
      baseAsset {
        assetId
        symbol
        iconUrl
      }
      quoteAsset {
        assetId
        symbol
        iconUrl
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
