query AdminUserDeprecatedOceanOrders($userId: ID!) {
  adminUserDeprecatedOceanOrders(userId: $userId) {
    traceId
    orderType
    side
    price
    baseAsset {
      assetId
      symbol
      iconUrl
    }
    quoteAsset {
      assetId
      symbol
      iconUrl
    }
    createdAt
  }
}
