query AdminAppletActivityConnection(
  $state: String
  $userId: ID
  $appletId: ID
  $after: String
) {
  adminAppletActivityConnection(
    state: $state
    userId: $userId
    appletId: $appletId
    after: $after
  ) {
    nodes {
      id
      state
      appletAction {
        type
        applet {
          id
          title
        }
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
