query AdminUserConnection($after: String, $query: String) {
  adminUserConnection(after: $after, query: $query) {
    nodes {
      id
      name
      avatar
      mixinId
      mixinUuid
      invitationsCount
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
