query AdminBookingOrderActivityConnection($after: String, $marketId: ID) {
  adminBookingOrderActivityConnection(after: $after, marketId: $marketId) {
    nodes {
      id
      startedAt
      endedAt
      bonusTotal
      scoresTotal
      validOrderSnapshotsCount
      market {
        baseAsset {
          assetId
          symbol
        }
        quoteAsset {
          assetId
          symbol
        }
      }
      bonusAsset {
        assetId
        symbol
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
