query AdminMixinNetworkSnapshotConnection($after: String, $oceanOrderId: ID) {
  adminMixinNetworkSnapshotConnection(
    after: $after
    oceanOrderId: $oceanOrderId
  ) {
    nodes {
      id
      type
      snapshotType
      traceId
      snapshotId
      amount
      data
      opponentId
      opponent {
        avatar
        name
        mixinId
      }
      asset {
        assetId
        symbol
        name
        iconUrl
      }
      processedAt
      transferredAt
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
