query AdminArbitrageOrder($id: ID!) {
  adminArbitrageOrder(id: $id) {
    id
    state
    netProfitUsd
    baseAssetProfit
    quoteAssetProfit
    raw
    arbitrager {
      name
      mixinUuid
    }
    market {
      baseAsset {
        assetId
        symbol
      }
      quoteAsset {
        assetId
        symbol
      }
    }
    createdAt
  }
}
